init 软件开发方法
TJ-CSCCG/TJCS-Course pull request #39
Opened 2022-07-04 08:41 UTC by lphlch

2022-07-04 11:16 UTC, skyleaworlder requested changes

2022-07-04 11:16 UTC, skyleaworlder commented on 100391_软件开发方法/README.md
> +可以发现，在教学大纲上，近半数内容（特别是 UML 图部分）与软件工程课程相似，可以达成互补的效果。如欲选择本门课程，强烈建议将其与软件工程放在一个学期内选择~~，这样你就可以不用听这门课了~~。
简单的格式问题，\~\~ 应该放在 “，” 之后。

2022-07-04 11:16 UTC, skyleaworlder commented on 100391_软件开发方法/README.md
> +* 熟悉使用 Java IDE 与 MySQL 的使用，编写 JDBC 链接 MySQL 的程序，实现增删改查等基本功能。
这里的无序列表使用了 “。”，而下方的无序列表每个 item 后却没有标点，建议统一一下格式。

2022-07-04 11:16 UTC, skyleaworlder commented on 100391_软件开发方法/README.md
> +期末项目的最后一个点对于熟悉 Java 开发的同学并不难，而对于从未接触过 Java 的大多数人，其难点在于在短短一学期内（噢对了，期末项目仅有两周时间来完成）**从零上手 Java 基础语法、 JDBC、 Java Web、 MVC 框架**等多个阶段（当然上课根本不会讲这些，需要自学）。
目前不建议使用 “（文字）” 的方式，还是用一种朴素平淡的语气叙述 “课程要求” 以及 “作业相关事宜”。

2022-07-04 11:16 UTC, skyleaworlder commented on 100391_软件开发方法/README.md
> +两次小作业分别为：
或许可以加一个 5 级标题来区分 “小作业” 和 “期末项目”。

（只是建议）

2022-07-04 11:53 UTC, lphlch commented on 100391_软件开发方法/README.md
> +可以发现，在教学大纲上，近半数内容（特别是 UML 图部分）与软件工程课程相似，可以达成互补的效果。如欲选择本门课程，强烈建议将其与软件工程放在一个学期内选择~~，这样你就可以不用听这门课了~~。
若是放在后面，那么删除后，逗号与句号之间没有任何的字，这样可以吗？

2022-07-04 13:01 UTC, skyleaworlder commented on 100391_软件开发方法/README.md
> +可以发现，在教学大纲上，近半数内容（特别是 UML 图部分）与软件工程课程相似，可以达成互补的效果。如欲选择本门课程，强烈建议将其与软件工程放在一个学期内选择~~，这样你就可以不用听这门课了~~。
哦哦，感觉有道理啊。所以不如用括号括起来（

2022-07-05 04:24 UTC, skyleaworlder approved these changes
LGTM!

2022-07-05 04:24 UTC, merged